name: "Edge Mining"
description: "An innovative solution to optimize the use of excess energy produced by small power plants, particularly domestic ones, integrating Bitcoin mining in the system, making it an easy-to-implement choice. This approach turns a potential inefficiency into a concrete opportunity for profit and sustainable energy use. "
version: "0.1.0"
slug: "edge_mining"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
hassio_api: true
hassio_role: manager
host_network: true
homeassistant_api: true
map:
  - type: homeassistant_config
    read_only: False
    path: /config/

options:
  broker_host: "homeassistant"
  miner_ip: "192.168.1.111"
  miner_username: "root"
  miner_password: "root"
schema:
  broker_host: str
  username: str?
  password: password?
  miner_ip: str
  miner_username: str
  miner_password: password